**NumPy = Numerical Python**

**What is NumPy?**

 NumPy is a Python library used for fast numerical operations using arrays.

 everything we do in data science needs numpy.




**Uses:**

 Math calculations

 Working with large data

 Data Science & Machine Learning



**Why better than list?**

✔ Faster

✔ Uses less memory

✔ Easy calculations (no loops needed)

✔ Supports multi-dimensional arrays

**pip  install numpy**

In [ ]:
nums = [1,2,3,4,5,6,7]
print(type(nums))

sq=[]
for n in nums:
  sq.append(n**2) # square the number from num list

print(sq)


<class 'list'>
[1, 4, 9, 16, 25, 36, 49]


In [ ]:
nums = [1,2,3,4,5,6,7,8]
sq=[x**2 for x in nums]
print(sq)

[1, 4, 9, 16, 25, 36, 49, 64]


In [2]:
import numpy

In [ ]:
arr = numpy.array([1,2,3,4,5])
print(arr)

print(type(arr))  # the diff in list and numpy is their is no comma in numpy

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
sq = arr**2
print(sq)

[ 1  4  9 16 25]


In [ ]:
cube = arr**3
print(cube)

[  1   8  27  64 125]


**Creating numpy array from 1D list**

In [ ]:
lst=[9,26,13,1,45,30,12,10,89,31]
arr = numpy.array(lst)

print(lst)
print(arr)
print(type(arr))

[9, 26, 13, 1, 45, 30, 12, 10, 89, 31]
[ 9 26 13  1 45 30 12 10 89 31]
<class 'numpy.ndarray'>


**Creating numpy array from 2D lists**

In [ ]:
lst = [
    [2,3,4,5],
    [6,7,8,9],
    [3,5,7,8]
]

print(lst)

[[2, 3, 4, 5], [6, 7, 8, 9], [3, 5, 7, 8]]


In [ ]:
arr = numpy.array(lst)
print(arr)

[[2 3 4 5]
 [6 7 8 9]
 [3 5 7 8]]


**Creating numpy array with 0's and 1's**

In [ ]:
z = numpy.zeros((4,5))
print(z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
o = numpy.ones((4,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr = numpy.full((3,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
arr = numpy.full((4,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


**Creating identity matrix**

In [6]:
arr = numpy.eye(3)          # Identity matrix
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = numpy.eye(2)
print(arr)

[[1. 0.]
 [0. 1.]]


In [ ]:
arr = numpy.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**create numpy array using arange()**

In [7]:
arr=numpy.arange(1,25)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [14]:
arr = numpy.arange(25,41)
print(arr)

[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [15]:
arr = numpy.arange(25,41,2)
print(arr)

[25 27 29 31 33 35 37 39]


In [18]:
arr = numpy.arange(25,1,-1)       # reverse by 1
print(arr)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [19]:
arr = numpy.arange(100,50,-5)     # reverse and diff is 5
print(arr)

[100  95  90  85  80  75  70  65  60  55]


**Linear spacing** in Python means creating numbers with equal gap (spacing) between them.

Mostly it is done using NumPy linspace() function.

**numpy.linspace(start, stop, number_of_values)**

In [20]:
x = numpy.linspace(1,10,5)
print(x)

# Explanation:

# Start = 1
# Stop = 10
# Total values = 5
# All numbers have equal spacing.

[ 1.    3.25  5.5   7.75 10.  ]


In [21]:
q = numpy.linspace(1,13,9)
print(q)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]


**Multiple types**

In [23]:
lst = ['Rohit',45,2.62,True]

for i in lst:
  print(type(i))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [26]:
arr = numpy.array(lst)
print(arr)                  # numpy array stored a homogenous data type

# All elements in NumPy array are of same data type.
# different types are given, NumPy converts them into one common type.

['Rohit' '45' '2.62' 'True']
