In [1]:
import numpy

In [3]:
arr = numpy.random.random(10)
print(arr)
print(type(arr))

[0.3422663  0.40240554 0.25450409 0.85273641 0.14607431 0.55147658
 0.85387661 0.40751542 0.36482434 0.40953232]
<class 'numpy.ndarray'>


**Random Int**

In [24]:
arr = numpy.random.randint(10)
print(arr)
  # only one random integer are return , not array, so don't use for loop here.
  # if yo want to use for loop here then give the size then every time its give a diff number on size

print()
print('BASED ON SIZE - Random number')
a = numpy.random.randint(10, size=3)

for i in a:
    print(i)

9

BASED ON SIZE - Random number
5
0
2


**"3x5 Random Numbers Array"**

In [26]:
print("Random 3x4 Array")

arr = numpy.random.random((3,4))
print(arr)

Random 3x5 Array
[[0.53679656 0.34422158 0.48786605 0.85215856]
 [0.14130773 0.33234744 0.39843551 0.64937642]
 [0.70714108 0.86059038 0.9770826  0.83708182]]


**10 Random Integers Between 1 and 50**

numpy.random.randint(start, end, size)

In [28]:
print('10 Random Integers Between 1 and 50:')

arr = numpy.random.randint(1,50,10)
print(arr)

10 Random Integers Between 1 and 50:
[36 22 17  8 31  2 10 45 28 33]


In [30]:
# numpy.random.randint(start, end, (rows, columns))

numpy.random.randint(11,30, (4, 3))

array([[21, 15, 13],
       [20, 29, 15],
       [14, 27, 15],
       [28, 13, 24]])

In [34]:
x = numpy.random.randint(1,100,(5,7))
print(x)

[[26 70 87 81 24 56 32]
 [95  7 38 72 39 17 41]
 [42 86 72 71 12 10 89]
 [89 28 28 39 33 58 30]
 [83 76 70 41 19 14 34]]
