In [4]:
import numpy

In [4]:
a1 = numpy.array([1,2,3,4])
a2 = numpy.array([7,5,8,9])

print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a2/a1)

[ 8  7 11 13]
[-6 -3 -5 -5]
[ 7 10 24 36]
[7.         2.5        2.66666667 2.25      ]


**Scaler Operations**

In [6]:
arr = numpy.array([1,2,3,4,5,6,7,8,9])
print(arr + 5)    # adding 5 in every element of arr
print(arr * 2)  # multiply every element by 2 in arr
print(arr**2) # pow by 2

[ 6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14 16 18]
[ 1  4  9 16 25 36 49 64 81]


**Aggregate Operations**

In [7]:
arr = numpy.array([1,2,3,4,5,6,7,8,9])
print(arr.sum())
print(arr.mean())
print(arr.std())
print(arr.var())
print(numpy.corrcoef(arr))
print(arr.max())
print(arr.min())

45
5.0
2.581988897471611
6.666666666666667
1.0
9
1


**Elementwise Operations**

In [8]:
arr = numpy.array([1,2,3,4,5,6,7,8])
print(numpy.sqrt(arr))
print(numpy.sin(arr))
print(numpy.cos(arr))
print(numpy.tan(arr))
print(numpy.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154]


**Rounding and absolute**

In [9]:
arr = numpy.array([1.4,3.6,-4,-5.7])
print(numpy.round(arr))
print(numpy.abs(arr))

[ 1.  4. -4. -6.]
[1.4 3.6 4.  5.7]


**Comparisons**

In [5]:
a1 = numpy.array([1,2,3])
a2 = numpy.array([4,2,5])

# Output of:
print(a1 == a2)

# [False  True False]

# Explanation:
# NumPy compares elements one by one

# 1 == 4  → False
# 2 == 2  → True
# 3 == 5  → False

# Therefore result becomes:
# [False  True False]
res = (a1==a2)


# Output of:
print(res.all())

# False

# Explanation:
# .all() checks whether ALL values inside the array are True or not.

# Result array is:
# [False  True False]

# Since the array contains False values,
# .all() returns False.

# If every value was True,
# then .all() would return True.

[False  True False]
False


In [15]:
print(a1 > a2)

[False False False]


In [9]:
a1=numpy.array([[12,23],[45,34],[65,49]])
a2=numpy.array([[11,23],[45,73],[71,49]])

comp = (a1 == a2)
print(comp)

print()

if comp.all():
  print("SAME VALUE")
else:
  print("DIFFRENT VALUE")

[[False  True]
 [ True False]
 [False  True]]

DIFFRENT VALUE


In [10]:
arr1 = numpy.array([[11,23],[45,77]])
arr2 = numpy.array([[11,23],[45,77]])

comp = (arr1 == arr2)
if comp.all():
  print("the numpy array have SAME VALUE ")
else:
  print("values in numpy is DIFFRENT ")

the numpy array have SAME VALUE 


**Cumulative Result**

In [12]:
# CUMULATIVE SUM - It continuously adds the elements one by one.

arr = numpy.array([1,2,3,4,5])
print(numpy.cumsum(arr))

[ 1  3  6 10 15]


In [13]:
# CUMULATIVE PRODUCT - It continuously multiplies the elements one by one.

arr = numpy.array([1,2,3,4,5])
print(numpy.cumprod(arr))

# Explanation :

# 2 = 2
# 2 × 3 = 6
# 2 × 3 × 4 = 24

[  1   2   6  24 120]
