In [1]:
import numpy

In [2]:
a1 = numpy.array([1,2,3,4,5])
a2 = numpy.array([10,20,30,40,50,60])
res = numpy.concatenate((a1,a2))
print(res)

[ 1  2  3  4  5 10 20 30 40 50 60]


In [10]:

a1 = numpy.array([[1,2,3],[4,5,6]])
a2 = numpy.array([[7,8,9],[10,11,12],[33,44,55]])

res = numpy.concatenate((a1,a2))

print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [33 44 55]]
