In [1]:
import numpy

In [2]:
arr = numpy.array([12,23,24,45,56,67,78,89,90])
print(arr)


[12 23 24 45 56 67 78 89 90]


In [3]:
print(arr[0])

12


In [5]:
print(arr[2:5])

[24 45 56]


In [7]:
print(arr[-1])

90


In [8]:
print(arr[::-1])  # reverse

[90 89 78 67 56 45 24 23 12]


In [9]:
print(arr[3:])   # after 3 index
print(arr[:4])  # before 4 index

[45 56 67 78 89 90]
[12 23 24 45]


In [11]:
lst = [
    [12,23,34,45,56],
    [54,43,32,21,76],
    [21,47,33,69,26]
]

arr = numpy.array(lst)
print(arr)

[[12 23 34 45 56]
 [54 43 32 21 76]
 [21 47 33 69 26]]


In [12]:
print(arr[0][0])

12


In [13]:
print(arr[:,:])   # all coloums anad rows

[[12 23 34 45 56]
 [54 43 32 21 76]
 [21 47 33 69 26]]


In [14]:
print(arr[2][3])

69


In [18]:
print(arr[1:,:])

[[54 43 32 21 76]
 [21 47 33 69 26]]
