In [1]:
import numpy

**Filter**

In [4]:
arr = numpy.random.randint(1,75,10)
print(arr)

[ 4 12 55 14  9 47 53 62  1 11]


In [5]:
filtered = arr[arr>50]
print(filtered)   # stering and then printing

[55 53 62]


In [6]:
print(arr[3:8])    # direct without stored

[14  9 47 53 62]


In [8]:
# direct without storing
print(arr[arr%2 == 0])
print(arr[arr%2 == 1])

[ 4 12 14 62]
[55  9 47 53  1 11]


**# SOME OPERATIIONS**

In [42]:
arr = numpy.array(['Prachi','Pooja','Sujal','akash','chiku','anay'])
print(arr)

['Prachi' 'Pooja' 'Sujal' 'akash' 'chiku' 'anay']


**1.startswith()**

In [43]:
print(arr[numpy.char.startswith(arr,'P')])

['Prachi' 'Pooja']


**2.endswith()**

In [45]:
print(arr[numpy.char.endswith(arr,"a")])

['Pooja']


**3.upper()**

In [46]:
print(numpy.char.upper(arr))

['PRACHI' 'POOJA' 'SUJAL' 'AKASH' 'CHIKU' 'ANAY']


**4.lower()**

In [47]:
print(numpy.char.lower(arr))

['prachi' 'pooja' 'sujal' 'akash' 'chiku' 'anay']


**5.replace()**

In [48]:
print(numpy.char.replace(arr,"a","@"))

['Pr@chi' 'Pooj@' 'Suj@l' '@k@sh' 'chiku' '@n@y']


**6.find()**

In [49]:
print(numpy.char.find(arr,"a"))   # -1 means character doesn't found

[ 2  4  3  0 -1  0]


**7.count()**

In [50]:
print(numpy.char.count(arr,"a"))

[1 1 1 2 0 2]


**8.split()**

In [52]:
a = numpy.array(["hello world", "numpy python"])

print(numpy.char.split(a))

[list(['hello', 'world']) list(['numpy', 'python'])]


**9.join()**

In [53]:
print(numpy.char.join("-",arr))

['P-r-a-c-h-i' 'P-o-o-j-a' 'S-u-j-a-l' 'a-k-a-s-h' 'c-h-i-k-u' 'a-n-a-y']


In [54]:
print(numpy.char.join("+",arr))

['P+r+a+c+h+i' 'P+o+o+j+a' 'S+u+j+a+l' 'a+k+a+s+h' 'c+h+i+k+u' 'a+n+a+y']


**10.sorting()**

In [64]:
arr1 = numpy.array(['Mohit','Ruru','Aakansha','yogesh','gulu','Anushka','Rahul'])
print(arr1)
print(numpy.sort(arr1))

['Mohit' 'Ruru' 'Aakansha' 'yogesh' 'gulu' 'Anushka' 'Rahul']
['Aakansha' 'Anushka' 'Mohit' 'Rahul' 'Ruru' 'gulu' 'yogesh']


**11. contains filtering**

In [65]:
print(arr1[numpy.char.find(arr1,"a")>=0])

['Aakansha' 'Anushka' 'Rahul']


**12. string length**

In [66]:
print(numpy.char.str_len(arr1))

[5 4 8 6 4 7 5]


**13. capitalize()**

In [67]:
print(numpy.char.capitalize(arr1))

['Mohit' 'Ruru' 'Aakansha' 'Yogesh' 'Gulu' 'Anushka' 'Rahul']


In [71]:
a = numpy.array(['hello world'])
print(numpy.char.capitalize(a))   # only the first letter

print()
print(numpy.char.title(a))   # every

['Hello world']

['Hello World']


**Sort**

In [16]:
arr = numpy.random.randint(1,20,10)
print(arr)  # NOTE - numpy allow a duplicate

[14  8  6 11  2  4 17  6 12 16]


In [17]:
print(numpy.sort(arr))

[ 2  4  6  6  8 11 12 14 16 17]


In [18]:
print(numpy.sort(arr)[::-1])   # reverse desc

[17 16 14 12 11  8  6  6  4  2]


**Unique**

In [20]:
arr = numpy.array([9,24,13,45,45,9,13,44,68])
print(arr)    # numpy easily stored a Duplicate value

[ 9 24 13 45 45  9 13 44 68]


In [22]:
# UNIQUE
un = numpy.unique(arr)
print(un)

[ 9 13 24 44 45 68]


**Split**

In [35]:
arr = numpy.array([9,24,13,55,99,33,45,45,68,88,77,99,67,67,33])
print(arr.shape)
print(len(arr))    # length of arr

print(numpy.split(arr,5))

(15,)
15
[array([ 9, 24, 13]), array([55, 99, 33]), array([45, 45, 68]), array([88, 77, 99]), array([67, 67, 33])]


In [36]:
arr = numpy.array([55,99,33,45,45,68,88,77,99,67,67,33])
print(arr.shape)
print(len(arr))    # length of arr

print(numpy.split(arr,5))   # ERROR - ValueError: array split does not result in an equal division


(12,)
12


ValueError: array split does not result in an equal division

In [38]:
arr = numpy.array([55,99,33,45,45,68,88,77,99,67,67,33])
print(arr.shape)
print(len(arr))    # length of arr

print(numpy.array_split(arr,5))

(12,)
12
[array([55, 99, 33]), array([45, 45, 68]), array([88, 77]), array([99, 67]), array([67, 33])]
